name: CI
on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, labeled, synchronize]
    branches:
      - release
  # push:
  #   branches:
  #     - release

jobs:
  docker-image:
    uses: ./.github/workflows/docker_image.yml
  build:
    runs-on: ubuntu-latest
    needs: [docker-image]
    container:
      image: ghcr.io/llnl/mgmol/mgmol_env:latest
      options: --user 1001 --privileged
      volumes:
        - /mnt:/mnt
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
      - name: Check out pylibROM
        uses: actions/checkout@v1
        with:
            submodules: 'true'
      - name: Git Submodules status
        run: |
            git submodule status
      - name: cmake
        run: |
            mkdir build
            cd build
            cmake .. -DCMAKE_CXX_COMPILER=mpic++ -DCMAKE_Fortran_COMPILER=mpif90
      - name: make
        run: |
            cd build && make -j 4
    
